from parts import *

Part ('control','control.parts', package_group='pkg_control')
Part ('msi','msi.parts', package_group='pkg6')
Part(
    'wixsample6','wixsample6.parts',toolchain = 'wix'
    )
