from parts import *
env= Environment(tools=[])

Part ('DEBIAN','control.parts', package_group='pkg_control')
Part ('dpkg_package1','dpkg_package1.parts', package_group='pkg1')

Part('packaging','packaging.parts')
PrintMessage(PackageGroups())

DefaultEnvironment().DPKGPackage('cpil', PackageGroups())

