from parts import *

from gen import generateTarball, TEST_TARBALL_NAME
import os

if not os.path.exists('%s.tar.gz' % TEST_TARBALL_NAME):
    # test tarball does not exist, create it
    generateTarball(TEST_TARBALL_NAME)

Part('extract.parts')
