from parts import *

Part ('control','control.parts', package_group='pkg_control')
Part ('msi','msi.parts', package_group='pkg1')
Part(
    'wixsample1','wixsample1.parts',toolchain = 'wix'
    )

