name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ['ubuntu:latest', 'almalinux:latest', 'fedora:latest']
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    container:
      image: ${{ matrix.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          version: "0.11.33"

      - name: Ubuntu system dependencies
        if: ${{ matrix.image == 'ubuntu:latest' }}
        run: |
          apt-get update
          apt-get install -y patchelf rpm procps git build-essential

      - name: Fedora System dependencies
        if: ${{ matrix.image == 'fedora:latest' }}
        run: |
          dnf install -y git procps-ng patchelf @development-tools

      - name: EL System dependencies
        if: ${{ matrix.image == 'almalinux:latest' }}
        run: |
          dnf install -y epel-release 'dnf-command(config-manager)'
          dnf config-manager --set-enabled crb
          dnf group install -y "Development Tools"
          dnf install -y patchelf git procps-ng

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Configure git
        run: |
          git config --global user.email "CI@github.com"
          git config --global user.name "GitHub Actions"

      - name: AuTests
        run: |
          uv run autest --version
          uv run autest -D ./tests/gold_tests

      - name: Pytest (non-fatal)
        continue-on-error: true
        run: |
          uv run pytest -v tests/unit --junitxml=test-reports/report.xml

      - name: Upload sandbox
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: sandbox-${{ matrix.python-version }}
          path: _sandbox/**

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-${{ matrix.python-version }}
          path: test-reports/report.xml
